{% set name = "sketchnu" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mhendrey/sketchnu/archive/v{{ version }}.tar.gz
  sha256: 2d8341acfd6fd41e9982116730da2a88c4913ee9efcb31cb4f2f5c0651b904ba

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - numba >=0.54.1
    - psutil
    - python >=3.8

test:
  imports:
    - sketchnu
  commands:
    - pip check
    - pytest
  requires:
    - pip
    - pytest

about:
  home: https://github.com/mhendrey/sketchnu
  summary: "Numba implementations of some sketch algorithms"
  description: |
    Numba implementations of the HyperLogLog++, count-min sketches with conservative
    updating & optional log-based counters, and topkapi heavy-hitters. Also, includes
    helper functions to use multiprocessing to speed up processing.
  license: GPL-3.0-or-later
  license_file: LICENSE
  doc_url: https://mhendrey.github.io/sketchnu
  dev_url: https://github.com/mhendrey/sketchnu

extra:
  recipe-maintainers:
    - mhendrey
